### ISSUE TITLE
Suggested feature #include

### ISSUE THREAD

**Issue by Karnor** [amtep/ck3-tiger#1]
I have a personal mod that is split over a couple of mods, also a few personal compatches.

I'm finding that running ck3-tiger over some of my mods, especially the compatches are throwing errors because ck3-tiger does not know about triggers, effects, modifiers, etc that are defined in other mods.

I personally think it would make the tool more useful if mods could be specified in an include = { } section in the conf file, so ck3-tiger could load them to resolve a lot of the associated errors.

ofc I would not want to see ck3-tiger actually process the include mods for errors/warning, just to use them as a source for resolution.

**Comment by amtep** [comment]
Yeah, processing only one mod at a time is a serious limitation of ck3-tiger. I was thinking of allowing multiple mods to be specified on the command line, but your idea is interesting too and may be an easier user interface.

The tool can treat those other mods in a similar way it currently treats vanilla CK3. (Where it doesn't report errors that are solely in vanilla but it does report vanilla lines that are related to a warning for the mod.) It may need additional smarts. For example if a compatch replaces a trigger that's used in a parent mod, and that replacement causes some errors in the parent mod, then those should be reported.

A lot of other things would have to change though. Like currently it reports filenames as either rooted in [CK3] or in [MOD]. It's going to have to specify which mod, to avoid confusion. Maybe the conf file can also specify which abbreviation to use for each mod. I guess by default it could go MOD1, MOD2, etc. In general, it currently tracks all file locations as either "ck3" or "mod", and adding the possibility of multiple mods will be a bit of work there.

**Comment by Karnor** [comment]
Yeah I knew there would a some issues with include files.

I thought it might be possible to dive into the included mod's descriptor.mod file to retrieve the mod name or it's workshop tag and use that to identify it, but some mod names are excessively long.

Personally I wouldn't mind having to specify a short identifying tag for the include mods or if they are simply marked INC1, INC2, etc

If you ever do get round to implementing include mods I think it will be hugely useful but no rush, these things take time.

**Comment by Karnor** [comment]
Going through a brutal task of updating my personal mod for the CK3AGOT Lance version which has really highlighted the need for an include mod feature.

I'm having to wade through a ton of noise generated by the AGOT trigger, effects, traits, etc that are not defined in my mod.

I know you cannot do anything atm, but just adding weight to the need for includes whenever you can work on the tool again.

**Comment by amtep** [comment]
I was kind of working on it today but had to set it aside for other changes :)

**Comment by amtep** [comment]
v0.5.0 is building now, it supports multiple mods :)

It was easier than I expected, and the code only got a little bit uglier.

**Comment by amtep** [comment]
I'll close this as implemented. The syntax is in the sample `ck3-tiger.conf` file, it looks like this:

```
load_mod = {
        label = "CFP"
        modfile = "/home/gamer/Pdx/mod/ugc_2220098919.mod"
}
```
