### ISSUE TITLE
False positive about warning(logic)

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#102]
Currently tiger will emit "warning(logic): setting value here will overwrite the previous calculations" if you use `value = xxx` in a script value's body (not the first line). This works for most situations, but it will cause false positive with `save_temporary_value_as`
Example:
```
da_value_max_3 = {
	if = {
		limit = { scope:_1 > scope:_2 }
		if = {
			limit = { scope:_1 > scope:_3 }
			value = scope:_1
		}
		else = {
			value = scope:_3
		}
	}
	else_if = {
		limit = { scope:_2 > scope:_3 }
		value = scope:_2
	}
	else = { value = scope:_3 }
}
da_test_value = {
	value = 100
	save_temporary_value_as = _1
	value = 200
	save_temporary_value_as = _2
	value = -100
	save_temporary_value_as = _3
	value = da_value_max_3
}
```
In this example, the paired `value = xxx` and `save_temporary_value_as = yyy` actually acts like *passing parameters* and then call a function, so perhaps we can suppress the warning if it follows a `save_temporary_value_as `? Or simply treat `save_temporary_value_as ` as the start of a new script value?

**Comment by amtep** [comment]
Thanks for the report :)

Tiger already tracks whether a script value has had "side effects" so it should be just a matter of checking that logic before complaining about the `value = `
