### ISSUE TITLE
TechnologyEra is never used

### ISSUE THREAD

**Issue by HiddeLekanne** [amtep/ck3-tiger#132]
The DBkind for TechnologyEra is never used, so it evaluates the eras.txt wrongly. I tried adjusting the currently wrong path (            Item::TechnologyEra => "common/technology//eras/",  to:   Item::TechnologyEra => "common/technology/technologies/eras/")

But that wasn't enough.

**Comment by amtep** [comment]
Hmm... it works for me. If I introduce an error into `common/technology/eras/00_eras.txt`, tiger reports it.

Can you give an example of what goes wrong?

**Comment by amtep** [comment]
Yeah I think you're using the wrong path for it. Vanilla has the eras in `common/technology/eras/`. By putting yours under `common/technology/technologies`, you're getting it validated as an `Item::Technology`.

**Comment by HiddeLekanne** [comment]
Nvm it is the wrong path

**Comment by HiddeLekanne** [comment]
ah yes xd

**Comment by amtep** [comment]
There's actually a relevant TODO for this :) Tiger should complain if you put a file in a too deep path. I think (but haven't verified) that only a few such as `common/defines/` and `events/` allow files in subdirectories.
