### ISSUE TITLE
Add new ep3 sound effects

### ISSUE THREAD

**Issue by unLomTrois** [amtep/ck3-tiger#138]
https://github.com/amtep/ck3-tiger/blob/cd237cf69318dab5dcd3a65a16e7e820151c7706/src/ck3/tables/misc.rs#L294

"unknown sound event:/DLC/EP3/SFX/UI/Contracts/ep3_ui_contracts_failure_on_contract"
"unknown sound event:/DLC/EP3/SFX/UI/Contracts/ep3_ui_contracts_success_on_contract"
"unknown sound event:/DLC/EP3/SFX/UI/Contracts/ep3_ui_contracts_accept_contract"

**Comment by ProZeratul** [comment]
Tiger is right, it's not an uppercased C but a lowercase one

**Comment by unLomTrois** [comment]
@ProZeratul but vanilla files uses Contracts with capital C, and because of case-sensitivity it creates errors in tiger.json
