### ISSUE TITLE
"claimant" field in setup_invasion_cb 

### ISSUE THREAD

**Issue by unLomTrois** [amtep/ck3-tiger#146]
Although setup_invasion_cb lacks claimant field in effects.log:
```txt
setup_invasion_cb - This effect will add a scope:cb_prestige_factor with a value based on what's being taken
setup_invasion_cb = {
	attacker = scope:attacker
	defender = scope:defender
	change = scope:change
	victory = yes/no
	take_occupied = yes/no
}
Supported Scopes: none
```

It uses this field in vanilla's cbs

![image](https://github.com/user-attachments/assets/b5c07eac-2979-435d-bd16-48f5975b73fd)

So, possiblly it inherits this field from setup_claim_cb effect:
```txt
setup_claim_cb - This effect will add a scope:cb_prestige_factor with a value based on what's being taken
Won't steal land from people not vassalized

setup_claim_cb = {
	attacker = scope:attacker
	defender = scope:defender
	claimant = scope:claimant
	change = scope:change
	victory = yes/no
	take_occupied = yes/no

	# Will vassalize people based on their capital location rather than being fully contained.
	civil_war = yes
}
Supported Scopes: none
```

Can you make it expect this field (claimant) in setup_invasion_cb as well? If it does not fully pass, then mark it as a warning and not an error.

**Comment by amtep** [comment]
I've looked at the cases where vanilla uses `setup_claim_cb` with `claimant = scope:claimant`, and those don't have a `scope:claimant` available. They are in event wars that are not called with a claimant.

Do you have an example where the `claimant =` is actually expected to work? Because without that, I think this is a bug in vanilla.

**Comment by amtep** [comment]
I did some debug logging for the hungarian invasion cb, and it seems that `scope:claimant` exists but is a null character. Also, the error.log does not complain about the `claimant` field in `setup_invasion_cb` even though it does complain about other random fields. So I guess tiger should accept it too.
