### ISSUE TITLE
setup_invasion_cb doesn't know about "claimant" field

### ISSUE THREAD

**Issue by unLomTrois** [amtep/ck3-tiger#15]
vanilla stuff

![image](https://github.com/amtep/ck3-tiger/assets/51882489/9c35d081-b68a-4c86-9ef7-02eca0a07e2f)

**Comment by amtep** [comment]
I actually think this is a copy paste error in vanilla, because it's in `setup_invasion_cb` and not `setup_claim_cb`.

The CB it's in is `hungarian_migration_cb` which I'm pretty sure has no claimant, just an attacker.
