### ISSUE TITLE
character_interactions/ai_potential lacks scopes 

### ISSUE THREAD

**Issue by unLomTrois** [amtep/ck3-tiger#151]
![378152111-29545ff7-3d89-4b56-8cca-91cc256e4a9f](https://github.com/user-attachments/assets/42792009-979e-45a3-8a3a-e30d581661d5)

**Comment by amtep** [comment]
Just because vanilla expects something doesn't mean it's correct ;)

See my comment here https://github.com/amtep/ck3-tiger/pull/150#issuecomment-2424612947

**Comment by unLomTrois** [comment]
Then I close it
