### ISSUE TITLE
false positive for landed title from barony?

### ISSUE THREAD

**Issue by Karnor** [amtep/ck3-tiger#2]
Scripted trigger pilgrimage_0500_valid_holy_site_trigger in pilgrimage_events.txt throwing this error

> [MOD] file events/activities/pilgrimage_activity/pilgrimage_events.txt
> line 285 			this = capital_province.barony
> line 285 			                        ^
> WARNING (scopes): `barony` produces landed title but expected character

The line numbers may be slightly off as it is a edited event but the trigger is untouched vanilla
```
scripted_trigger pilgrimage_0500_valid_holy_site_trigger = {
	#... we really shouldn't talk about the holy site we might be _in_ right now / invalid capital_province holy site
	NOR = { 
		this = root.location.barony
		AND = {
			exists = capital_province
			this = capital_province.barony
		}
	}
}

```

**Comment by ProZeratul** [comment]
This is not a false positive, you are in an any_holy_site scope that produce landed title but landed title does not have a capital_province, so the warning is good, you should have:

exists = root.capital_province 
this = root. capital_province.barony

**Comment by amtep** [comment]
Yeah. Since you're doing `capital_province` (implicitly on `this`), `this` must be a character. But in order to be equal to `capital_province.barony`, `this` must be a barony. `ck3-tiger` flags this inconsistency.
