### ISSUE TITLE
Update the main message for error(filename)

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#22]
The current main message for error(filename) is a constant 'file in unexpected directory', which has no effective information
Perhaps we could add the quoted filename and/or directory to the main message so that it can be filtered using `text`
For example, when I update my mod for a new version, I usually move some of my files/folders into a special `.obsolete` folder, and I'd like tiger to only ignore files in this folder, however, due to the insufficient main message of error(filename), I can only ignore the whole `filename` key

**Comment by amtep** [comment]
This makes sense, though the duplication in the full message woukd bother me a little
