### ISSUE TITLE
[False positive] vic3-tiger misunderstand `modifier` and `modifer_type`

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#29]
In Victoria 3, the folder `common/modifier` contains detailed modifiers which can be added directly to an entity (country, character, etc.)
While the folder `common/modifier_type` contains modifier types that may be used in modifiers or something else, it can also be accessed via `modifier:xxx`.

Currently, vic3-tiger outputs `error(missing-item): modifier XXX not defined in common/modifiers/` when the mod accesses user-defined modifier types, however, actually it should read from `common/modifier_types` to find user-defined modifier types

**Comment by amtep** [comment]
This is easy enough to fix, but the existence of user-defined modifier types will change some things about the validation generally. I first noticed them in law definitions, and I'm not sure how to accept them without giving up on warning about misspelled modifiers at all.

As far as I know, the entry in `common/modifier_types` is optional and is only used for displaying the modifier in the UI.

**Comment by amtep** [comment]
I made PR#31 for thus issue

**Comment by amtep** [comment]
Fixed with PR#31
