### ISSUE TITLE
false positive for operator >=

### ISSUE THREAD

**Issue by Karnor** [amtep/ck3-tiger#3]
Scripted trigger courtier_guest_management_1001_exceptional_marriage_candidate_trigger in courtier_guest_management_events.txt throwing this error

> [MOD] file events/courtier_guest_management_events/courtier_guest_management_events.txt
> line 393 				TIER >= scope:host.highest_held_title_tier
> line 393 				^
> ERROR (validation): expected `TIER =` or `?=`, found `>=`
> 
```
			marriage_between_characters_unlocks_alliance_of_min_tier_trigger = {
				MY_CHARACTER = scope:host
				THEIR_CHARACTER = scope:marriage_candidate
				TIER >= scope:host.highest_held_title_tier
			}

```

**Comment by amtep** [comment]
The error message is subtly wrong though :) It says expected TIER = or ?=
But ?= would be wrong here too.

**Comment by amtep** [comment]
Specifying exactly where ?= is valid will be a big task...

**Comment by amtep** [comment]
There's also a question, if this >= syntax is harmless should we still warn about it?
I'm leaning toward "yes warn", because someone might think <= will also work and it won't.

**Comment by amtep** [comment]
I adjusted the error messages so that it will no longer imply ?= can be used here. I think that ties up the last of the threads from this report
