### ISSUE TITLE
[False positive] vic3-tiger should allow `script value block` anywhere requires a value

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#30]
Currently vic3-tiger will output `error(structure): expected value, found block` for using in-place script value block instead of a direct value, which is allowed in the game engine

Example: 
```
s:STATE_ALSACE_LORRAINE = {
    add_arable_land = {
        value = region_state:FRA.arable_land
        multiply = 0.5
    }
}
```

**Comment by amtep** [comment]
Is it really anywhere? These are the effects where tiger currently expects an Integer rather than a ScriptValue:

* add_arable_land
* add_commander_rank
* add_devastation
* add_enactment_phase
* add_enactment_setback
* add_escalation
* add_pollution
* set_commander_rank
* set_devastation

* progress in add_technology_progress
* investment in change_institution_investment_level
* months in end_truce

It's mostly because a ScriptValue would allow fractions and fractional values don't make sense there.

**Comment by dragon-archer** [comment]
I'd like to test fraction in more effects later, but now I found a similar bug: The integer trigger is not mutual, that is, it doesn't even accept itself!

Example:
```
s:STATE_ALSACE_LORRAINE = {
	add_arable_land = region_state:FRA.arable_land
}
```

The validator outputs `error(validation): expected integer`, however triggers like `arable_land` CAN actually be used as value(also integer)

**Comment by dragon-archer** [comment]
> Is it really anywhere? These are the effects where tiger currently expects an Integer rather than a ScriptValue:
> 
> * add_arable_land
> * add_commander_rank
> * add_devastation
> * add_enactment_phase
> * add_enactment_setback
> * add_escalation
> * add_pollution
> * set_commander_rank
> * set_devastation
> * progress in add_technology_progress
> * investment in change_institution_investment_level
> * months in end_truce
> 
> It's mostly because a ScriptValue would allow fractions and fractional values don't make sense there.

OK I've tested most of these effects, and I had to say the engine is very tricky, note that all these effects accept negative numbers and fractions.

Effect|Allow value block|Fraction behaviour with direct number|Fraction behaviour inside block|Notes
---|---|---|---|---
add_arable_land|✅|Round to zero|Round to nearest
add_commander_rank|❌|Round to zero|N/A
add_devastation|✅|Round to zero|Round to zero|Only the tooltip, the actual effect can handle fraction correctly
add_enactment_phase|✅|Round to zero|Round to nearest
add_enactment_setback|✅|Round to zero|Round to nearest
add_escalation|❌|Round to zero|N/A
add_pollution|✅|Round to zero|Round to zero|Only the tooltip, the actual effect is strange and even may not be linear
set_commander_rank|❌|Round to zero|N/A|Negative is allowed but treated as 1
set_devastation|✅|Round to zero|Round to zero|Only the tooltip, the actual effect can handle fraction correctly, however, negative numbers have no effect and the tooltip is also positive(This might be a paradox bug for missing _neg localization)
add_technology_progress|❌|Nearly accurate|N/A|Actually round to zero with 2 decimal's precisions
change_institution_investment_level|❌|Round to zero|N/A
end_truce|✅|Round to zero|Round to nearest|Only tooltip, actual effect not tested

**Comment by amtep** [comment]
Oh I should have checked here before pushing my latest commit :)
