### ISSUE TITLE
[Feature] Some new (or missing) modifiers in Vic 1.5.13

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#32]
- `limited_to_frontier_colonization` in `common/laws/00_colonial_affairs.txt`, with a boolean argument (not documented but used in original game file)
- `show_as_unavailable` in all event options, it's actually a trigger block (not documented but can work)
- `min_hiring_rate`, `max_hiring_rate`, and `ignores_productivity_when_hiring` in building_groups (documented in info and used in original game file)
- `city_lights_color_index` in production_methods of urban center (not documented but used in origianl game file at least since 1.4.0)
- `group` in jounal entries (documented and used)

**Comment by amtep** [comment]
I fixed these except for the journal entries `group`, which will require loading the journal entry groups which it currently doesn't do
