### ISSUE TITLE
[Bug] console option `--unused` can't recognize vanilla game usage

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#33]
When using `vic3-tiger` with `--unused` switched on and with either `--show-vanilla` switched on or off, the validator will output thousands of unused items, and most of them are in the vanilla game, also they're actually used.

**Comment by amtep** [comment]
Yeah I see it too. I haven't investigated the code yet

**Comment by amtep** [comment]
I fixed the issue with it showing vanilla items.

It showing false positives will have to be dealt with on a case by case basis; there's no way to fix that completely. In fact I created the --unused feature in order to find things that tiger didn't validate yet, and it's an ongoing process.
