### ISSUE TITLE
Possible false positives for missing field

### ISSUE THREAD

**Issue by Karnor** [amtep/ck3-tiger#4]
I get these errors but this is vanilla syntax and it's used quite a lot throughout vanilla, with no error log complaints, so not sure if this is legal syntax or not.
```
line 19847 		any_relation = { this = root }
line 19847 		               ^
ERROR (field-missing): required field `type` missing
```

**Comment by ProZeratul** [comment]
@Karnor This is not a false positive, this is indeed an error and all vanilla code using it is to be treated as bugged

**Comment by amtep** [comment]
Yeah, we've both verified this :) any_relation without a type just does nothing
