### ISSUE TITLE
Random crash error

### ISSUE THREAD

**Issue by dragon-archer** [amtep/ck3-tiger#82]
![image](https://github.com/amtep/ck3-tiger/assets/45531248/a0671815-7a45-4cad-a97a-81a1a696dba4)

As shown in the image, it seems that vic3-tiger crashes randomly, because I didn't change anything between the two runs.
The same crash error has occured twice, though I should say it's still relatively rare.

**Comment by amtep** [comment]
I can't reproduce it but I think I figured out the cause. A commit to fix it is in PR#83

**Comment by amtep** [comment]
Fixed in PR#83
