### ISSUE TITLE
thread '<unnamed>' panicked at 'index out of bounds: the len is 13 but the index is 211', src\ck3\data\interaction_cats.rs:71:42

### ISSUE THREAD

**Issue by ssebaa** [amtep/ck3-tiger#96]
Hello!

So I decided to try to become a modder for ck3 and for the milestone in it I set the updating an old mod. However, I failed at setupping ck3-tiger correctly for days now 😔. I come to concussion that there may be a bug within tiger code because it would be very embarrassing if that was iust my fault and I'm apologizing already to for it🙏. So this is how i tried to launch it(I tried many ways, this error appears the most).
```
PS E:\Narzedzia do modow\ck3\tiger> .\ck3-tiger.exe --ck3 "c:/Games/Steam/steamapps/common/Crusader Kings III" "c:/Games/Steam/steamapps/workshop/content/1158310/2218620123/descriptor.mod"
This validator was made for Crusader Kings version 1.12.3 (Scythe).
If you are using a newer version of Crusader Kings, it may be inaccurate.
!! Currently it's inaccurate anyway because it's in beta state.
Using CK3 directory: c:/Games/Steam/steamapps/common/Crusader Kings III
Using mod directory: c:/Games/Steam/steamapps/workshop/content/1158310/2218620123

thread '<unnamed>' panicked at 'index out of bounds: the len is 13 but the index is 211', src\ck3\data\interaction_cats.rs:71:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS E:\Narzedzia do modow\ck3\tiger>
```
As I couldn't find the mentioned file ```src\ck3\data\interaction_cats.rs``` in my ck3 directory so I tried by verifying integrity of files, no success. I don't know what to do I really want to make mods for this game and this tool seems essential to me. I would be very grateful for help.
Thanks for the reading and have a nice day!

**Comment by my4ng** [comment]
Hi @ssebaa, thanks for the issue! It does appear to be a bug on initial inspection, and we will be fixing this as soon as possible. You can build from source or wait and download the next release when we complete the fix and close this issue!

**Comment by ssebaa** [comment]
Thank you and have a nice day!

**Comment by amtep** [comment]
Today's release 0.9.4 fixes this bug :) Thank you for reporting it!
