### ISSUE TITLE
Tiger seems to have trouble with long files

### ISSUE THREAD

**Issue by ssebaa** [amtep/ck3-tiger#98]
![image](https://github.com/amtep/ck3-tiger/assets/60935038/ad92be80-3944-4df7-b5d2-90354762bf44)
![image](https://github.com/amtep/ck3-tiger/assets/60935038/19ac660b-5eef-4150-af3d-176321b1722f)
2 shots of the same file after 2 scans. It may be vscode extension fault, if so I apologize🙏

**Comment by ssebaa** [comment]
UPDATE: This seems to happen only for messages. Alerts and errors still show later in the file so it may be intended mechanic but idk

**Comment by amtep** [comment]
Yeah this is most likely a limitation in either vscode itself or the plugin for vscode. `ck3-tiger` emits errors and warnings before lower-priority messages, so anything that cuts off the number of messages after some amount will have this behavior of still showing the important stuff.

The plugin for vscode is developed by user unLomTrois at this repository: [ck3tiger-for-vscode](https://github.com/unLomTrois/ck3tiger-for-vscode)

github doesn't allow transferring issues to other users, so it's best if  you file this issue again in that repository.

**Comment by ssebaa** [comment]
Alrighty, thanks for the response! Will make an issue on the proper repo when I get on my pc
